/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE DATABASE IF NOT EXISTS `aqtdb2` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `aqtdb2`;

/*!40000 ALTER TABLE `tconfig` DISABLE KEYS */;
INSERT INTO `tconfig` (`id`, `pass1`, `TCODE`, `encval`, `proto`, `diffc`) VALUES
	(1, 'testadmin', 'K001', 'MS949', '0', 'AND (a.rcode <> b.rcode )');
/*!40000 ALTER TABLE `tconfig` ENABLE KEYS */;

/*!40000 ALTER TABLE `tlevel` DISABLE KEYS */;
INSERT INTO `tlevel` (`lvl`, `lvl_nm`, `svc_cnt`, `data_cnt`, `scnt`) VALUES
	('1', '0', 296, 1221, 1175),
	('2', '0', 6, 9, 0);
/*!40000 ALTER TABLE `tlevel` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
